Feature#47 structure and style cart screen
BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team2 pull request #50
Opened 2023-04-06 00:23 UTC by AangelF

# Description
I create the base of the carrito screen, is the structure and styles only, for in the future issues add functionality, take data from a request to the API.

## Screenshots

![image](https://user-images.githubusercontent.com/60322727/230242108-1f2c0145-31a6-4d01-904d-ddce061f2d3d.png)

2023-04-06 00:41 UTC, carloso0114 approved these changes

2023-04-06 09:07 UTC, Reiyirak approved these changes

2023-04-10 19:04 UTC, YilKanda requested changes

2023-04-10 19:04 UTC, YilKanda commented on app/views/cart/index.html.erb
> +</main>
Check the indentation of your file.

Add a blank line.

2023-04-10 19:04 UTC, YilKanda commented on app/views/partials/_phone_card_cart.html.erb
> +</section>
Check the indentation of your file.

2023-04-11 21:56 UTC, merged