Feature#33 about us page
BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team2 pull request #64
Opened 2023-04-20 22:36 UTC by AangelF

# Description

What did you implemented/Why did you implemented this:

Create a about us page to explain the user about our page web and the services can provide it.

## Screenshots

![image](https://user-images.githubusercontent.com/60322727/233501264-cbac4b25-34a0-44f6-8ae9-23305f2914a5.png)

2023-04-20 23:52 UTC, DiegoMoralesBravo approved these changes

2023-04-21 01:46 UTC, JuanequeX requested changes

2023-04-21 01:46 UTC, JuanequeX commented on app/helpers/about_us_helper.rb
> +end
if this helper is unnecessary please remove it

2023-04-21 01:46 UTC, JuanequeX commented on app/views/about_us/index.html.erb
> +</div>
add a blank line at the end of this file

2023-04-21 01:46 UTC, JuanequeX commented on app/views/partials/_footer.html.erb
> +          <a href="#"><h5 class="fw-bold text-black"> Sobre Nosotros </h5></a>
remove the `h5` label is unnecessary if you have an `a` wrapped in it

2023-04-21 01:46 UTC, JuanequeX commented on test/controllers/about_us_controller_test.rb
> +end
it will be cool if adding tests for this controller

2023-04-21 22:33 UTC, oscaregr approved these changes

2023-04-25 03:18 UTC, JuanequeX approved these changes

2023-04-25 19:26 UTC, merged